from django.conf import settings
from django.urls import path
from django.conf.urls.static import static
from.import views

urlpatterns = [
  path('',views.index,name=""),
  path('index',views.index,name="index"),
  path('admin',views.admin,name="admin"),
  path('adminhome',views.adminhome,name="adminhome"),
  path('providerlist',views.providerlist,name="providerlist"),
  path('login',views.login,name="login"),
  path('plotlist/',views.plotlist,name="plotlist"),
  path('userlist',views.userlist,name="userlist"),
  path('bookinglist',views.bookinglist,name="bookinglist"),
  path('commissionlist',views.commissionlist,name="commissionlist"),
  path('complaintlist',views.complaintlist,name="complaintlist"),
  path('feedbacklist',views.feedbacklist,name="feedbacklist"),
  path('paymentlist',views.paymentlist,name="paymentlist"),
  path('logout',views.logout,name="logout"),
  path('adprivacy',views.adprivacy,name="adprivacy"),
  path('userreg',views.userreg,name="userreg"),
  path('provreg',views.provreg,name="provreg"),
  path('provider/',views.provider,name="provider"),
  path('providerhome/',views.providerhome,name="providerhome"),
  path('regplot/',views.regplot,name="regplot"),
  path('viewplots/',views.viewplots,name="viewplots"),
  path('addslots/',views.addslots,name="addslots"),
  path('parking/',views.parking,name="parking"),
  path('staff_complaints/',views.staff_complaints,name="staff_complaints"),
  path('complaints/',views.complaints,name="complaints"),
  path('change/',views.change,name="change"),
  path('feedback/',views.feedback,name="feedback"),
  path('prpaylist/',views.prpaylist,name="prpaylist"),
  path('viewbooking/',views.viewbooking,name="viewbooking"),
  path('payadmin/',views.payadmin,name="payadmin"),
  path('viewcancellation/',views.viewcancellation,name="viewcancellation"),
  path('provprofile/',views.provprofile,name="provprofile"),
  path('user/',views.user,name="user"),
  path('book/',views.book,name="book"),
  path("bookapproval",views.bookapproval,name="bookapproval"),
  path('proprivacy/',views.proprivacy,name="proprivacy"),
  path('bklist/',views.bklist,name="bklist"),
  path('pbklist/',views.pbklist,name="pbklist"),
  path('parkslots/',views.parkslots,name="parkslots"),
  path('fd/',views.fd,name="fd"),
  path('search/',views.search,name="search"),
  path('shedule/',views.shedule,name="shedule"),
  path('plot/',views.plot,name="plot"),
  path('approvepro/',views.approvepro,name="approvepro"),
  path('rejectpro/',views.rejectpro,name="rejectpro"),
  path('deletecomplaint/',views.deletecomplaint,name="deletecomplaint"),
  path('deletefeedback/',views.deletefeedback,name="deletefeedback"),
  path('approveplot/',views.approveplot,name="approveplot"),
  path('rejectplot/',views.rejectplot,name="rejectplot"),
  path('slot/',views.slot,name="slot"),
  path('slot1/',views.slot1,name="slot1"),
  path('slot2/',views.slot2,name="slot2"),
  path('updateprof/',views.updateprof,name="updateprof"),
  path('slotbukapproval',views.slotbukapproval,name="slotbukapproval"),
  path('getLocation',views.getLocation,name=" getLocation"),
  path('add_location',views.add_location,name="add_location"),
  path('getDistrict',views.getDistrict,name="getDistrict"),
  path('request_payment',views.request_payment,name="request_payment"),
  path('waiting_payment',views.waiting_payment,name="waiting_payment"),
  path('payment_request',views.payment_request,name="payment_request"),
  path('payment_completed',views.payment_completed,name="payment_completed"),
  path('payment_history',views.payment_history,name="payment_history"),
  path("bookslotapprove",views.bookslotapprove,name="bookslotapprove"),
  path("payment_requestpro",views.payment_requestpro,name="payment_requestpro"),
  path("payment_completedpro",views.payment_completedpro,name="payment_completedpro"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)