# Generated by Django 3.2.13 on 2022-08-02 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0004_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='plot',
            fields=[
                ('plotid', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=50, verbose_name='name')),
                ('place', models.CharField(max_length=50, verbose_name='place')),
                ('location', models.CharField(max_length=50, verbose_name='location')),
                ('totalarea', models.CharField(max_length=50, verbose_name='totalarea')),
                ('plan', models.FileField(upload_to='', verbose_name='plan')),
                ('twowheeler', models.CharField(max_length=50, verbose_name='twowheeler')),
                ('tworate', models.CharField(max_length=50, verbose_name='tworate')),
                ('twocapacity', models.CharField(max_length=50, verbose_name='twocapacity')),
                ('twocommission', models.CharField(max_length=50, verbose_name='twocommission')),
                ('threewheeler', models.CharField(max_length=50, verbose_name='threewheeler')),
                ('threerate', models.CharField(max_length=50, verbose_name='threerate')),
                ('threecapacity', models.CharField(max_length=50, verbose_name='threecapacity')),
                ('threecommission', models.CharField(max_length=50, verbose_name='threecommission')),
                ('fourwheeler', models.CharField(max_length=50, verbose_name='fourwheeler')),
                ('fourrate', models.CharField(max_length=50, verbose_name='fourrate')),
                ('fourcapacity', models.CharField(max_length=50, verbose_name='fourcapacity')),
                ('fourcommission', models.CharField(max_length=50, verbose_name='fourcommission')),
                ('status', models.CharField(max_length=50, verbose_name='status')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smart.provider')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('feedbackid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(max_length=50, verbose_name='date')),
                ('feedback', models.CharField(max_length=150, verbose_name='feedback')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smart.provider')),
            ],
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('complaintid', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=50, verbose_name='subject')),
                ('date', models.DateField(max_length=50, verbose_name='date')),
                ('complaint', models.CharField(max_length=150, verbose_name='complaint')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smart.provider')),
            ],
        ),
    ]
