# Generated by Django 3.2.13 on 2022-08-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0005_complaint_feedback_plot'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='temp',
            field=models.CharField(default=1, max_length=25, verbose_name='temp'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plot',
            name='plan',
            field=models.FileField(upload_to='images/', verbose_name='plan'),
        ),
        migrations.AlterField(
            model_name='user',
            name='license',
            field=models.FileField(max_length=50, upload_to='images/', verbose_name='license'),
        ),
    ]
