# Generated by Django 3.2.13 on 2022-08-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0006_auto_20220804_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='status',
            field=models.CharField(default=1, max_length=50, verbose_name='status'),
            preserve_default=False,
        ),
    ]
