# Generated by Django 3.2.13 on 2022-08-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0007_provider_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='fourwheeler',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plot',
            name='threewheeler',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plot',
            name='twowheeler',
            field=models.BooleanField(default=False),
        ),
    ]
