# Generated by Django 3.2.13 on 2022-08-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0008_auto_20220805_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='fourwheeler',
            field=models.CharField(max_length=50, verbose_name='fourwheeler'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='threewheeler',
            field=models.CharField(max_length=50, verbose_name='threewheeler'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='twowheeler',
            field=models.CharField(max_length=50, verbose_name='twowheeler'),
        ),
    ]
