# Generated by Django 3.2.13 on 2022-08-05 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0009_auto_20220805_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='slot',
            fields=[
                ('slotid', models.AutoField(primary_key=True, serialize=False)),
                ('slotname', models.DateField(max_length=50, verbose_name='slotname')),
                ('status', models.CharField(max_length=50, verbose_name='status')),
                ('slotplotid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smart.plot')),
            ],
        ),
    ]
