# Generated by Django 3.2.13 on 2022-08-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0010_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='slotname',
            field=models.CharField(max_length=50, verbose_name='slotname'),
        ),
    ]
