# Generated by Django 3.2.13 on 2022-08-09 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0011_alter_slot_slotname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='address',
            field=models.CharField(max_length=150, verbose_name='address'),
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('bookingid', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smart.user')),
            ],
        ),
    ]
