# Generated by Django 3.2.9 on 2022-09-01 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0012_auto_20220809_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='plot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smart.plot'),
        ),
    ]
