# Generated by Django 3.2.9 on 2022-09-14 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0013_booking_plot'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='providers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smart.provider'),
        ),
    ]
