# Generated by Django 3.2.9 on 2022-09-27 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0014_booking_providers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plot',
            name='fourcapacity',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='fourcommission',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='fourrate',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='threecapacity',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='threecommission',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='threerate',
        ),
    ]
