# Generated by Django 3.2.9 on 2022-09-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0015_auto_20220927_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='fourcapacity',
            field=models.CharField(default=1, max_length=50, verbose_name='fourcapacity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plot',
            name='fourcommission',
            field=models.CharField(default=1, max_length=50, verbose_name='fourcommission'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plot',
            name='fourrate',
            field=models.CharField(default=1, max_length=50, verbose_name='fourrate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plot',
            name='threecapacity',
            field=models.CharField(default=1, max_length=50, verbose_name='threecapacity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plot',
            name='threecommission',
            field=models.CharField(default=1, max_length=50, verbose_name='threecommission'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plot',
            name='threerate',
            field=models.CharField(default=1, max_length=50, verbose_name='threerate'),
            preserve_default=False,
        ),
    ]
