# Generated by Django 3.2.14 on 2022-09-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0019_auto_20220930_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='bank',
            fields=[
                ('bank_id', models.AutoField(primary_key=True, serialize=False)),
                ('holder', models.CharField(max_length=100, verbose_name='holder')),
                ('card', models.CharField(max_length=100, verbose_name='card')),
                ('cvv', models.CharField(max_length=100, verbose_name='cvv')),
                ('exp', models.CharField(max_length=100, verbose_name='exp')),
                ('bal', models.CharField(max_length=100, verbose_name='bal')),
            ],
        ),
    ]
