# Generated by Django 3.2.14 on 2022-09-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0020_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default=1, max_length=100, verbose_name='status'),
            preserve_default=False,
        ),
    ]
