# Generated by Django 3.2.9 on 2022-10-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0022_alter_login_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='plot',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='providers',
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=50, verbose_name='username'),
        ),
    ]
