# Generated by Django 3.2.9 on 2022-10-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0024_auto_20221001_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='amt',
            field=models.CharField(default=1, max_length=100, verbose_name='amt'),
            preserve_default=False,
        ),
    ]
