# Generated by Django 3.2.9 on 2022-10-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0025_slot_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='commission_amt',
            field=models.CharField(default=1, max_length=100, verbose_name='commission_amt'),
            preserve_default=False,
        ),
    ]
