# Generated by Django 3.2.9 on 2022-10-04 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0026_slot_commission_amt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='complaintid',
            new_name='complaint_id',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='provider',
            new_name='staff',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='feedbackid',
            new_name='feedback_id',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='date',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='date',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='provider',
        ),
        migrations.AddField(
            model_name='complaint',
            name='msg',
            field=models.CharField(default=1, max_length=500, verbose_name='message'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='reply',
            field=models.CharField(default=1, max_length=500, verbose_name='reply'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='sub',
            field=models.CharField(default=1, max_length=200, verbose_name='sublect'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='reply',
            field=models.CharField(default=1, max_length=500, verbose_name='reply'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smart.user'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.CharField(max_length=500, verbose_name='feedback'),
        ),
    ]
