# Generated by Django 3.2.9 on 2022-10-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0027_auto_20221004_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='sub',
            field=models.CharField(default=1, max_length=200, verbose_name='sublect'),
            preserve_default=False,
        ),
    ]
