# Generated by Django 4.1.2 on 2022-10-08 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0028_feedback_sub'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('commission', models.IntegerField()),
                ('available', models.IntegerField()),
                ('plot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart.plot')),
            ],
        ),
    ]
